const constants = {
    GAME_TYPE_BLITZ : "blitz",
    GAME_TYPE_RAPID : "rapid",
    GAME_TYPE_BULLET : "bullet",

	// BULLET
	GAME_TIME_CONTROL_60_0  : "60-0",
	GAME_TIME_CONTROL_60_1  : "60-1",
	GAME_TIME_CONTROL_120_0 : "120-0",

	// BLITZ
	GAME_TIME_CONTROL_180_0 : "180-0",
	GAME_TIME_CONTROL_180_1 : "180-1",
    GAME_TIME_CONTROL_300_0 : "300-0",

	// RAPID
	GAME_TIME_CONTROL_600_0  : "600-0",
	GAME_TIME_CONTROL_900_0  : "900-0",
	GAME_TIME_CONTROL_1200_0 : "1200-0",

	CHARACTER_PAWN : "p", 
	CHARACTER_KNIGHT : "n", 
	CHARACTER_KING : "k",
	CHARACTER_QUEEN : "q",
	CHARACTER_BISHOP : "b",
	CHARACTER_ROOK : "r",
	CHARACTER_EVOLVED_PAWN : "e",

	SKILL_ENLIGHTENED_APPRENTICE : "Enlightened Apprentice", 
	SKILL_THE_GREAT_WALL : "The Great Wall",
	SKILL_FOG_MASTER : "Fog Master", 
	SKILL_FREEZING_WAND : "Freezing Wand",
	SKILL_PARALYZER : "Paralyzer",
}

export default constants