const constants = {
    WS_EVENT_MATCHMAKING : "MATCHMAKING",
    WS_EVENT_START_GAME : "START_GAME", 
    WS_EVENT_CONNECT_GAME : "CONNECT_GAME",

    WS_EVENT_UPDATE_GAME_STATE : "UPDATE_GAME_STATE", 
    WS_EVENT_GAME_PUBLISH_ACTION : "GAME_PUBLISH_ACTION",
    WS_EVENT_END_GAME : "END_GAME",
    WS_EVENT_GET_GAME_DURATION : "GET_GAME_TIME_DURATION",
    WS_EVENT_RECEIVE_GAME_TIME_DURATION : "GAME_TIME_DURATION",
}

export default constants