const constants = {
    WS_EVENT_MATCHMAKING : "MATCHMAKING",
    WS_EVENT_START_GAME : "START_GAME", 
    WS_EVENT_CONNECT_GAME : "CONNECT_GAME",

    WS_EVENT_UPDATE_GAME_STATE : "UPDATE_GAME_STATE", 
    WS_EVENT_GAME_PUBLISH_ACTION : "GAME_PUBLISH_ACTION",
}

export default constants